### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ksdmitrieva** [luh2/DetectDynamicJS#14]
Hello,

This is just a question. 

@amitamathkar and myself have a few updates to DetectDynamicJS plugin that remove some of false positives, that we would like to commit. Is there a contributor agreement that must be signed before contributing? The work was done as part of a corporate engagement, so we have to do the paperwork itnernally first.

Thanks,
Ksenia

**Comment by luh2** [comment]
Hi @ksdmitrieva 
Looking forward to your pull request. If it is structured in small commits, it'll be easier for me to review before accepting. 
There is no contributor agreement. I'll be happy to put your GitHub handles into the Thanks list on the starting page though.
