### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by 1lastBr3ath** [luh2/DetectDynamicJS#5]
"A picture is worth a thousand words", please take a look.

![response2](https://cloud.githubusercontent.com/assets/7494618/15990456/6fb25d06-30b2-11e6-9d34-fe668cf74bf5.png)
![request1](https://cloud.githubusercontent.com/assets/7494618/15990452/6edaba36-30b2-11e6-9c16-7c66f2e02f1e.png)
![response1](https://cloud.githubusercontent.com/assets/7494618/15990453/6ef2207c-30b2-11e6-893a-2156e3dd73e8.png)
![request2](https://cloud.githubusercontent.com/assets/7494618/15990454/6ef97c32-30b2-11e6-897c-50318337bb6c.png)
![content-type-html](https://cloud.githubusercontent.com/assets/7494618/15990530/daf6b312-30b4-11e6-98c5-0fcfdc024d3e.png)

Issues address in screenshots;
1. Duplicate reports
2. Second request also being sent as POST
4. Content-Length ignored
5. Status Code ignored
6. Content-Type ignored

I'm also working on it. If you had used 'inferredMimeType', I don't think it would have processed xml or html contents. Also, ignoring the '<' char if appeared first (as I had done previously), would reduce these false positives to some extent. The second request needs to be GET, ignoring the base request method. Content-length being ignored might be due to improper checking, and duplicate reports, ma be due to difference in parameters. 

I'm also working on it, let me know if you have anything.

**Comment by luh2** [comment]
Well aware of all of them. Just didn't bother me too much yet. About 
#1: That one was on my list as next thing to implement. Patch coming soon (meaning about 2-3 weeks). 
#2: Is second on my list as things to implement. I'm not just going to drop POST, but see the other thread about this. If this can be done efficiently with Burp's API, I'm happy :) If the change from POST to GET (shifting the parameters to URL) returns a different answer, this should be a a finding. But not a Detected Dynamic JS, but exactly that behavior and criticality low.
#4: There is a Content-Length check somewhere, will have to see why that one it. 
#5: Status code is addressed in the other comment on the [first pull request](https://github.com/luh2/DetectDynamicJS/pull/1).
#6: Content-Type is totally unreliable. It almost has to be ignored. As example: Yahoo sometimes sends script files as `application/json` .

**Comment by luh2** [comment]
Number #4 and #5 are taken care of. #6 will have to stay that way for now. #1 and #2 are added to the wiki in the ToDo list.

**Comment by luh2** [comment]
#2 fixed in 9e2e8047bb1f8391f9a80f41f7d9eb5562434e40
